stages:
  - provision

provision_infra:
  stage: provision
  # Imagen con Ansible preinstalado para simplificar
  image: williamyeh/ansible:alpine3
  script:
    - ansible-playbook -i "localhost," -c local playbook.yml
  # Variables de entorno para GCP (puedes usar GitLab CI/CD Variables)
  # Asegúrate de proporcionar credenciales de GCP adecuadas (service account JSON)
  # y exportar la variable GCLOUD_SERVICE_ACCOUNT_KEY, etc.
  variables:
    GCP_PROJECT_ID: "TU_PROYECTO_GCP"
    GCP_ZONE: "us-central1-a"
  only:
    - main  # o la rama que desees