stages:
  - provision

provision_infra:
  stage: provision
  image: google/cloud-sdk:alpine
  script:
    - apk update && apk add --no-cache py3-pip bash
    - pip3 install --break-system-packages ansible google-auth google-auth-httplib2 google-api-python-client
    - ansible-galaxy collection install google.cloud --ignore-errors || true
    - echo "$GCLOUD_SERVICE_ACCOUNT_KEY_B64" | base64 -d > /tmp/gcloud_service_account.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcloud_service_account.json
    - ansible-playbook -i "localhost," -c local playbook.yml
  only:
    - main
