---
- name: Configure Jenkins VM for passwordless sudo
  hosts: all
  become: yes
  tasks:
    - name: Add jenkins user to sudoers for passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^jenkins '
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

- name: Set global Jenkins environment variable
  hosts: all
  become: yes
  tasks:
    - name: Create Groovy script to set global environment variable
      template:
        src: set_global_env.groovy.j2
        dest: /tmp/set_global_env.groovy
        mode: '0755'
    - name: Download Jenkins CLI jar
      shell: wget http://localhost:8080/jnlpJars/jenkins-cli.jar -O /tmp/jenkins-cli.jar
    - name: Run Groovy script via Jenkins CLI
      shell: java -jar /path/to/jenkins-cli.jar -s http://localhost:8080/ groovy = < /tmp/set_global_env.groovy
