---
- name: Configure Jenkins VM for secure access
  hosts: all
  become: yes
  tasks:
    - name: Enable security in Jenkins config.xml
      replace:
        path: /var/lib/jenkins/config.xml
        regexp: '<useSecurity>false</useSecurity>'
        replace: '<useSecurity>true</useSecurity>'
      notify: Restart Jenkins

    - name: Ensure jenkins user has passwordless sudo privileges
      lineinfile:
        dest: /etc/sudoers
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

  handlers:
    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted
