---
- name: Configure Jenkins VM for passwordless sudo
  hosts: all
  become: yes
  tasks:
    - name: Add jenkins user to sudoers for passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^jenkins '
        line: 'jenkins ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'
